
window.classes = [
  {
    "class_id":345,
    "class_name":"Vinyasa ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_day":"Monday",
    "class_start":"6:00 AM",
    "class_duration":60,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees."
  },
  {
    "class_id":346,
    "class_name":"Advanced Yoga",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Jasha",
    "teacher_name":"Jasha",
    "class_day":"Monday",
    "class_start":"9:30 AM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":9,
    "attr_spirit":9,
    "attr_flex":8,
    "attr_balance":10,
    "_attr_tempo":6,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":"0",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":"Advanced Yoga:\nFrom the traditional roots of yoga this advanced class is designed to take your yoga practice deeper. \n\nStrengthen your body using movement, find peace using meditation and invite transformation using breath work and sound. You will be carefully guided to find new ways to approach familiar postures as well as exploring new ones in a playful way.\n\nFind out why yoga is more than just a workout by finding beauty within each breath."
  },
  {
    "class_id":347,
    "class_name":"Kundalini ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Kirtan",
    "teacher_name":"Kirtan",
    "class_day":"Monday",
    "class_start":"10:45 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":8,
    "attr_flex":6,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam."
  },
  {
    "class_id":348,
    "class_name":"Lunch Break Power Flow",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Sarah",
    "teacher_name":"Sarah",
    "class_day":"Monday",
    "class_start":"12:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":8,
    "attr_balance":6,
    "_attr_tempo":8,
    "difficulty":2,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":"A mid-day pick-me-up. Slow down and re-charge with an empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students and modifications for newer students. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Leave class inspired, peaceful & energized."
  },
  {
    "class_id":349,
    "class_name":"Yoga ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Jasha",
    "teacher_name":"Jasha",
    "class_day":"Monday",
    "class_start":"12:15 PM",
    "class_duration":60,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":"Experience balance and peace in this hour long class. Focus your attention inward while we will take the traditional practice of yoga into a modern design, tailored to our community. Each day will be different. Whether you come once a month or three times a week, It will be well rounded and include a theme that rotates weekly to include all aspects of yoga, physical and non-physical, each month. Join in this sweet practice, honoring the full spectrum of life and ourselves."
  },
  {
    "class_id":350,
    "class_name":"Conscious Kick Boxing",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Briana",
    "teacher_name":"Briana",
    "class_day":"Monday",
    "class_start":"2:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":10,
    "attr_spirit":9,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":10,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":"0",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":351,
    "class_name":"Liquid Flow w/ Sacred Sound",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Amanda",
    "class_day":"Monday",
    "class_start":"3:30 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":8,
    "attr_flex":8,
    "attr_balance":8,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":"A multi-level class designed for new and experienced students. There will be progressive options offered in many asanas so that each person will be challenged at their level. A variety of new asanas will be practiced each class to explore and build upon your current practice. Expect a dynamic class which is a creative blend, emphasizing the union of breath, body, and mind. Classes are joyous and infused with a sense of play."
  },
  {
    "class_id":352,
    "class_name":"All Levels Power Vinyasa Yoga",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"candice",
    "teacher_name":"Candice",
    "class_day":"Monday",
    "class_start":"5:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":8,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees."
  },
  {
    "class_id":353,
    "class_name":"Vinyasa Flow",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Aliza",
    "teacher_name":"Aliza",
    "class_day":"Monday",
    "class_start":"5:15 PM",
    "class_duration":75,
    "class_end":"6:30 PM",
    "attr_strength":6,
    "attr_spirit":7,
    "attr_flex":5,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"0",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students and modifications for newer students. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm."
  },
  {
    "class_id":354,
    "class_name":"Power Vinyasa Level 2/3 ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_day":"Monday",
    "class_start":"6:30 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":10,
    "attr_spirit":9,
    "attr_flex":10,
    "attr_balance":9,
    "_attr_tempo":9,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":"0",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students including vigorous sequences and advanced postures. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Heated to enhance flexibility and endurance. Come ready to breath, sweat, and open up! Heated 85-90 degrees."
  },
  {
    "class_id":355,
    "class_name":"Restorative Kundalini Yoga and Meditation",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Vikki",
    "teacher_name":"Vikki",
    "class_day":"Monday",
    "class_start":"6:45 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":1,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":2,
    "_attr_tempo":1,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"0",
    "node_beginner":"1",
    "class_description":"Turn Your Monday BLAH’S into Monday AHH’sMore than just a set of physical exercises, Kundalini Yoga is a science and technology designed to heal at the very core. In each Kundalini yoga class we use a powerful combination of postures, breath, sound, meditation, and relaxation to strengthen the body, calm the mind and awaken the spirit. In this restorative class, we begin with calming breath to quiet the mind and soothe the nervous system. Moving into a gentle posture sequence, we synchronize our breath and movement, dissolving the deeply held tension in the body. As the energy begins to move, we find greater balance as we reconnect to our center. From this open and relaxed space, we flow into extended mantra and meditation, followed by a deep relaxation. Body, mind and spirit will be touched, loved and deeply nourished. No prior yoga experience is necessary. Class is suitable for all levels and ages."
  },
  {
    "class_id":356,
    "class_name":"Intro to Contact Improvisation",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Jenna",
    "class_day":"Monday",
    "class_start":"8:15 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":7,
    "attr_flex":6,
    "attr_balance":6,
    "_attr_tempo":9,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"0",
    "node_beginner":"0",
    "class_description":"Contact Improvisation is a revolution: an opportunity to follow bodily sensations in a mutually dependent dialogue of weight-bearing, a discovery of the mystery of movement through non-doing. Postmodern and genre-defying, CI is based on a rolling point of physical contact between dancers who yield to each other’s bodies to create a fluid exchange of weight. In this class, we will expand upon improvisation as a metaphor for life: exploring movement as a vehicle for expression and a means for engaging spontaneously and creatively with our surroundings. The class will incorporate a variety of performance techniques including voice and theatre, Somatics and breath work, authentic movement, and jamming in order to celebrate the mind-body connection and hone our instruments as human beings. Open to dancers, actors, writers, artists, yogis, and musicians of all abilities and ages! No previous dance experience required. "
  },
  {
    "class_id":358,
    "class_name":"Goddess Circle",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Amanda",
    "class_day":"Monday",
    "class_start":"8:30 PM",
    "class_duration":60,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":7,
    "attr_flex":6,
    "attr_balance":6,
    "_attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":"We start with a little bit of yoga and open up into group meditation creating a safe space to explore, support, grow and thrive."
  },
  {
    "class_id":359,
    "class_name":"Vinyasa",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_day":"Tuesday",
    "class_start":"6:30 AM",
    "class_duration":65,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":6,
    "attr_flex":6,
    "attr_balance":5,
    "_attr_tempo":5,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"0",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":360,
    "class_name":"Soul Shine Yoga",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"jennifer",
    "teacher_name":"Jennifer",
    "class_day":"Tuesday",
    "class_start":"8:00 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":6,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":361,
    "class_name":"Yoga and Meditation",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Peggy",
    "class_day":"Tuesday",
    "class_start":"9:15 AM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":3,
    "attr_spirit":8,
    "attr_flex":8,
    "attr_balance":3,
    "_attr_tempo":3,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"0",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":362,
    "class_name":"Cardio Dance",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Briana",
    "teacher_name":"Briana",
    "class_day":"Tuesday",
    "class_start":"9:30 AM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":8,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":363,
    "class_name":"All Levels Power Vinyasa Yoga ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_day":"Tuesday",
    "class_start":"12:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":364,
    "class_name":"Vinyasa Basics",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Asha",
    "class_day":"Tuesday",
    "class_start":"12:15 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":6,
    "attr_flex":6,
    "attr_balance":6,
    "_attr_tempo":5,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":365,
    "class_name":"Acu-Intuitive Flow",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_day":"Tuesday",
    "class_start":"2:15 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":7,
    "attr_flex":6,
    "attr_balance":6,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":366,
    "class_name":"Power Vinyasa",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Yoni",
    "class_day":"Tuesday",
    "class_start":"3:30 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":367,
    "class_name":"Yoga Flow",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"jennifer",
    "teacher_name":"Jennifer",
    "class_day":"Tuesday",
    "class_start":"3:45 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":368,
    "class_name":"Prana Flow",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Pixie",
    "teacher_name":"Pixie",
    "class_day":"Tuesday",
    "class_start":"5:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":8,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":369,
    "class_name":"Restorative & Yin Yoga",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"deborah",
    "teacher_name":"Deborah",
    "class_day":"Tuesday",
    "class_start":"5:15 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":1,
    "attr_spirit":2,
    "attr_flex":1,
    "attr_balance":1,
    "_attr_tempo":1,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"0",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":370,
    "class_name":"Power Vinyasa Level 2/3",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_day":"Tuesday",
    "class_start":"6:30 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":10,
    "attr_spirit":10,
    "attr_flex":10,
    "attr_balance":9,
    "_attr_tempo":9,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":371,
    "class_name":"Vinyasa Flow",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_day":"Tuesday",
    "class_start":"6:45 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":7,
    "attr_flex":5,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":null,
    "node_injuries":"",
    "node_stand":"",
    "node_meditation":"",
    "node_chanting":"",
    "node_core":"",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":372,
    "class_name":"Eclectic Yin Yang",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_day":"Tuesday",
    "class_start":"8:15 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":4,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":373,
    "class_name":"Kundalini",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_day":"Tuesday",
    "class_start":"8:30 PM",
    "class_duration":60,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":8,
    "attr_flex":6,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":374,
    "class_name":"Vinyasa",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_day":"Wednesday",
    "class_start":"6:00 AM",
    "class_duration":60,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":7,
    "attr_flex":5,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":null,
    "node_injuries":"",
    "node_stand":"",
    "node_meditation":"",
    "node_chanting":"",
    "node_core":"",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":375,
    "class_name":"Kundalini ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Vikki",
    "teacher_name":"Vikki",
    "class_day":"Wednesday",
    "class_start":"7:45 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":7,
    "attr_flex":6,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":376,
    "class_name":"Pilates-Yoga Fusion, All Levels ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Arianna",
    "class_day":"Wednesday",
    "class_start":"8:00 AM",
    "class_duration":60,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":377,
    "class_name":"AyurYoga Flow",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Kellen",
    "teacher_name":"Kellen",
    "class_day":"Wednesday",
    "class_start":"9:15 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":7,
    "attr_flex":6,
    "attr_balance":6,
    "_attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":378,
    "class_name":"Prana Flow ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Pixie",
    "teacher_name":"Pixie",
    "class_day":"Wednesday",
    "class_start":"9:30 AM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":8,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":379,
    "class_name":"All Levels Power Vinyasa Yoga ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_day":"Wednesday",
    "class_start":"12:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":6,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":380,
    "class_name":"Yoga",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Jasha",
    "teacher_name":"Jasha",
    "class_day":"Wednesday",
    "class_start":"12:15 PM",
    "class_duration":60,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":4,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":381,
    "class_name":"Yoga Schmoga ~ Community Class",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Patrick",
    "class_day":"Wednesday",
    "class_start":"3:30 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":3,
    "attr_spirit":6,
    "attr_flex":6,
    "attr_balance":7,
    "_attr_tempo":4,
    "difficulty":1,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":382,
    "class_name":"Conscious Kick Boxing",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Briana",
    "teacher_name":"Briana",
    "class_day":"Wednesday",
    "class_start":"5:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":10,
    "attr_spirit":9,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":10,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":383,
    "class_name":"Slow Motion",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_day":"Wednesday",
    "class_start":"5:15 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":6,
    "attr_flex":6,
    "attr_balance":6,
    "_attr_tempo":5,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":384,
    "class_name":"Power Vinyasa Level 2/3",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_day":"Wednesday",
    "class_start":"6:30 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":10,
    "attr_spirit":10,
    "attr_flex":9,
    "attr_balance":10,
    "_attr_tempo":9,
    "difficulty":3,
    "node_heated":10,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":385,
    "class_name":"Restorative Yoga",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Leigh",
    "class_day":"Wednesday",
    "class_start":"6:45 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":3,
    "attr_spirit":2,
    "attr_flex":2,
    "attr_balance":1,
    "_attr_tempo":1,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"0",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":386,
    "class_name":"Partner Yoga & Flying",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Arianna",
    "class_day":"Wednesday",
    "class_start":"8:15 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":4,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"0",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":387,
    "class_name":"Hathalini ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Chyla & Kirtan",
    "class_day":"Thursday",
    "class_start":"7:45 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":8,
    "attr_flex":6,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":388,
    "class_name":"Yoga and Meditation",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Peggy",
    "class_day":"Thursday",
    "class_start":"9:15 AM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":5,
    "attr_flex":5,
    "attr_balance":3,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"0",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":389,
    "class_name":"Pilates-Yoga Fusion, Hot Level 2",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Arianna",
    "class_day":"Thursday",
    "class_start":"9:30 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":8,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":8,
    "difficulty":2,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":390,
    "class_name":"All Levels Power Vinyasa Yoga ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_day":"Thursday",
    "class_start":"12:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":391,
    "class_name":"Vinyasa Basics ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Asha",
    "class_day":"Thursday",
    "class_start":"12:15 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":7,
    "difficulty":1,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":392,
    "class_name":"Power Vinyasa",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Yoni",
    "class_day":"Thursday",
    "class_start":"3:30 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":393,
    "class_name":"Aroma Slow Flow Yoga",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Jenn",
    "class_day":"Thursday",
    "class_start":"3:45 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":9,
    "attr_flex":7,
    "attr_balance":4,
    "_attr_tempo":1,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"0",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":394,
    "class_name":"Power Vinyasa Level 2/3",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_day":"Thursday",
    "class_start":"5:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":10,
    "attr_spirit":10,
    "attr_flex":10,
    "attr_balance":9,
    "_attr_tempo":9,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":395,
    "class_name":"Vinyasa Flow",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_day":"Thursday",
    "class_start":"5:15 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":396,
    "class_name":"Prana Flow",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Pixie",
    "teacher_name":"Pixie",
    "class_day":"Thursday",
    "class_start":"6:30 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":8,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":397,
    "class_name":"Restorative Kundalini Yoga and Meditation",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Vikki",
    "teacher_name":"Vikki",
    "class_day":"Thursday",
    "class_start":"6:45 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":3,
    "attr_spirit":4,
    "attr_flex":3,
    "attr_balance":3,
    "_attr_tempo":3,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":398,
    "class_name":"Ecstatic Groove",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Studio",
    "teacher_image":"",
    "teacher_name":"Bri and Quest",
    "class_day":"Thursday",
    "class_start":"8:30 PM",
    "class_duration":120,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":5,
    "attr_flex":2,
    "attr_balance":5,
    "_attr_tempo":10,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"0",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":399,
    "class_name":"Vinyasa ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_day":"Friday",
    "class_start":"6:00 AM",
    "class_duration":60,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":400,
    "class_name":"Kundalini ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Amritpreet",
    "class_day":"Friday",
    "class_start":"7:45 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":3,
    "attr_spirit":10,
    "attr_flex":0,
    "attr_balance":0,
    "_attr_tempo":3,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"0",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":401,
    "class_name":"Good Morning Power Flow",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Aliza",
    "teacher_name":"Aliza",
    "class_day":"Friday",
    "class_start":"8:00 AM",
    "class_duration":60,
    "class_end":"",
    "attr_strength":9,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":5,
    "_attr_tempo":8,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"0",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":402,
    "class_name":"Slow Motion",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_day":"Friday",
    "class_start":"9:30 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":6,
    "attr_flex":4,
    "attr_balance":5,
    "_attr_tempo":4,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"0",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":403,
    "class_name":"Vinyasa/Medical Chi Gong",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_day":"Friday",
    "class_start":"10:30 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":404,
    "class_name":"All Levels Power Vinyasa Yoga",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_day":"Friday",
    "class_start":"12:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":405,
    "class_name":"Yoga ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Jasha",
    "teacher_name":"Jasha",
    "class_day":"Friday",
    "class_start":"12:15 PM",
    "class_duration":60,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":406,
    "class_name":"All Levels Power Vinyasa Yoga",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Rachel Meisler",
    "class_day":"Friday",
    "class_start":"3:30 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"0",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":408,
    "class_name":"Power Vinyasa All Levels",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"candice",
    "teacher_name":"Candice",
    "class_day":"Friday",
    "class_start":"5:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":8,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":409,
    "class_name":"Kundalini",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Mitsuko",
    "class_day":"Friday",
    "class_start":"5:15 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":7,
    "attr_flex":6,
    "attr_balance":7,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":410,
    "class_name":"Restorative & Yin Yoga",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"deborah",
    "teacher_name":"Deborah",
    "class_day":"Friday",
    "class_start":"6:30 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":1,
    "attr_spirit":2,
    "attr_flex":1,
    "attr_balance":1,
    "_attr_tempo":1,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"0",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":412,
    "class_name":"Morning Practice",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Vikki",
    "teacher_name":"Vikki",
    "class_day":"Saturday",
    "class_start":"9:15 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":3,
    "attr_spirit":10,
    "attr_flex":0,
    "attr_balance":0,
    "_attr_tempo":3,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"0",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":413,
    "class_name":"Power Vinyasa Level 2/3",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_day":"Saturday",
    "class_start":"9:30 AM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":10,
    "attr_spirit":9,
    "attr_flex":10,
    "attr_balance":9,
    "_attr_tempo":9,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":"0",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":414,
    "class_name":"Shimmy, Shake and Flow ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Arianna",
    "class_day":"Saturday",
    "class_start":"11:15 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":6,
    "attr_flex":6,
    "attr_balance":6,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":415,
    "class_name":"Power Vinyasa All Levels ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_day":"Saturday",
    "class_start":"11:30 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":6,
    "attr_balance":6,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":417,
    "class_name":"Qi Gong ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Russell",
    "class_day":"Saturday",
    "class_start":"4:30 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":7,
    "attr_flex":5,
    "attr_balance":7,
    "_attr_tempo":4,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"0",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":418,
    "class_name":"Vinyasa Basics ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Sarah",
    "teacher_name":"Sarah",
    "class_day":"Saturday",
    "class_start":"4:30 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":7,
    "difficulty":1,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":420,
    "class_name":"Liquid Flow with Sacred Sound",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_day":"Sunday",
    "class_start":"9:15 AM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":7,
    "attr_flex":6,
    "attr_balance":6,
    "_attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":421,
    "class_name":"Kundalini ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Kirtan",
    "teacher_name":"Kirtan",
    "class_day":"Sunday",
    "class_start":"9:30 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":8,
    "attr_flex":6,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":422,
    "class_name":"All Levels Power Vinyasa Yoga",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_day":"Sunday",
    "class_start":"11:00 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":8,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":423,
    "class_name":"Dharma Yoga and Qigong",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Chloë",
    "class_day":"Sunday",
    "class_start":"11:15 AM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":8,
    "attr_flex":8,
    "attr_balance":2,
    "_attr_tempo":2,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"0",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":424,
    "class_name":"Power Vinyasa ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Yoni",
    "class_day":"Sunday",
    "class_start":"12:30 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":425,
    "class_name":"Capoeira Pacifica",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Sean",
    "class_day":"Sunday",
    "class_start":"4:00 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":5,
    "attr_spirit":5,
    "attr_flex":7,
    "attr_balance":9,
    "_attr_tempo":8,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"0",
    "node_stand":"0",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":426,
    "class_name":"Eclectic Flow",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Brett",
    "teacher_name":"Brett",
    "class_day":"Sunday",
    "class_start":"5:00 PM",
    "class_duration":75,
    "class_end":"",
    "attr_strength":6,
    "attr_spirit":7,
    "attr_flex":6,
    "attr_balance":7,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"1",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  },
  {
    "class_id":427,
    "class_name":"Kirtan and Sacred Music",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Jacob",
    "class_day":"Sunday",
    "class_start":"6:00 PM",
    "class_duration":120,
    "class_end":"",
    "attr_strength":0,
    "attr_spirit":8,
    "attr_flex":0,
    "attr_balance":0,
    "_attr_tempo":0,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":"1",
    "node_stand":"0",
    "node_meditation":"1",
    "node_chanting":"1",
    "node_core":"0",
    "node_beginner":"1",
    "class_description":""
  },
  {
    "class_id":428,
    "class_name":"Vinyasa Flow - Community Class ",
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_day":"Sunday",
    "class_start":"6:30 PM",
    "class_duration":90,
    "class_end":"",
    "attr_strength":7,
    "attr_spirit":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":"1",
    "node_stand":"1",
    "node_meditation":"0",
    "node_chanting":"0",
    "node_core":"1",
    "node_beginner":"0",
    "class_description":""
  }
];