window.classes = [
  {
    "class_name":"Vinyasa Flow",
    "class_id":1,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_start":"6:30 AM",
    "class_end":"7:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":8,
    "attr_flex":6,
    "attr_balance":8,
    "_attr_tempo":10,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Vinyasa flow links breath with movement. Tiff's classes are challenging, but with teired levels so all can participate. Be ready to sweat!",
    "node_music":"",
    "short_description":"Get ready to sweat! This class is challenging, but with tiered levels for varied practitioner levels, all can participate.",
    "unique_pitch":"This is a breath-based practice that weaves in music and spirituality, while incorporating a good workout, taboot!"
  },
  {
    "class_name":"Gyrokinesis/Yoga for Dancers",
    "class_id":2,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Karen",
    "class_start":"8:45 AM",
    "class_end":"9:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":7,
    "attr_flex":6,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":4,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"This is a movement class based on elements of Hatha , and Kundalini Yoga. An organized, and flowing progression of seated, standing, and lying sequences. These breath and rhythm inspired sequences stimulate the senses, move energy, and create space in the body. Thus feeling more like a dance, than like that of a traditional Yoga class.This class provides a way to create flexibility and connection in the body. Also, a great tool in assisting performance in dance, athletics, and all other movement modalities. For all levels.",
    "node_music":0,
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Strong Flow",
    "class_id":3,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_start":"9:30 AM",
    "class_end":"10:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":6,
    "_attr_tempo":7,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Chyla’s class will challenge you to push your edge while reminding you to stay soft and open. Expect a fun yet strong practice with soulful connection and her latest fresh playlist!",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Kundalini",
    "class_id":4,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Kirtan",
    "class_start":"10:00 AM",
    "class_end":"11:15 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":5,
    "attr_flex":6,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Lunch Break Power Flow",
    "class_id":5,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Sarah",
    "teacher_name":"Sarah",
    "class_start":"12:00 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":7,
    "attr_flex":8,
    "attr_balance":6,
    "_attr_tempo":8,
    "difficulty":2,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"A mid-day pick-me-up. Slow down and re-charge with an empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students and modifications for newer students. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Leave class inspired, peaceful & energized.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Yoga ",
    "class_id":6,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_start":"12:15 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Experience balance and peace in this hour long class. Focus your attention inward while we will take the traditional practice of yoga into a modern design, tailored to our community. Each day will be different. Whether you come once a month or three times a week, It will be well rounded and include a theme that rotates weekly to include all aspects of yoga, physical and non-physical, each month. Join in this sweet practice, honoring the full spectrum of life and ourselves.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":7,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Jordan",
    "class_start":"3:45 PM",
    "class_end":"5:00 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":7,
    "attr_flex":6,
    "attr_balance":8,
    "_attr_tempo":5,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students and modifications for newer students. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm.",
    "node_music":1,
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Power Vinyasa Yoga ",
    "class_id":8,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"candice",
    "teacher_name":"Candice",
    "class_start":"5:00 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":8,
    "attr_flex":6,
    "attr_balance":8,
    "_attr_tempo":8,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":1,
    "short_description":"This class poses an accessible challenge. It's good to have some yoga background or attend beginning classes when you start my class. Expect a rhythmic flow of postures and movements, deep breathing, and a workout on all levels: body, mind, spirit!",
    "unique_pitch":"It's hard, but not ridiculously hard - it's supposed to feel good! You will hear unique music and do movements inspired by my dance background. People like that I am fun / happy / funny. :)"
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":9,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Aliza",
    "teacher_name":"Aliza",
    "class_start":"5:15 PM",
    "class_end":"6:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":7,
    "attr_flex":5,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Vinyasa links breath with movement. Aliza's class will challenge and uplift you and she always ends with delicious stretches.",
    "node_music":1,
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Power Vinyasa Level 2/3 ",
    "class_id":10,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":10,
    "attr_flex":10,
    "attr_balance":9,
    "_attr_tempo":9,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students including vigorous sequences and advanced postures. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Heated to enhance flexibility and endurance. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Restorative Kundalini Yoga and Meditation",
    "class_id":11,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Vikki",
    "teacher_name":"Vikki",
    "class_start":"6:45 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":1,
    "attr_flex":7,
    "attr_balance":2,
    "_attr_tempo":1,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Turn Your 1 BLAH’S into 1 AHH’sMore than just a set of physical exercises, Kundalini Yoga is a science and technology designed to heal at the very core. In each Kundalini yoga class we use a powerful combination of postures, breath, sound, meditation, and relaxation to strengthen the body, calm the mind and awaken the spirit. In this restorative class, we begin with calming breath to quiet the mind and soothe the nervous system. Moving into a gentle posture sequence, we synchronize our breath and movement, dissolving the deeply held tension in the body. As the energy begins to move, we find greater balance as we reconnect to our center. From this open and relaxed space, we flow into extended mantra and meditation, followed by a deep relaxation. Body, mind and spirit will be touched, loved and deeply nourished. No prior yoga experience is necessary. Class is suitable for all levels and ages.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Goddess Yoga Circle",
    "class_id":12,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Amanda",
    "class_start":"8:30 PM",
    "class_end":"9:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":1,
    "attr_flex":1,
    "attr_balance":6,
    "_attr_tempo":1,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"We start with a little bit of yoga and open up into group meditation creating a safe space to explore, support, grow and thrive.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":13,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Bettina",
    "class_start":"6:30 AM",
    "class_end":"7:35 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":null,
    "_attr_tempo":7,
    "difficulty":null,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Kundalini Yoga",
    "class_id":14,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Vikki",
    "teacher_name":"Vikki",
    "class_start":"8:30 AM",
    "class_end":"9:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":null,
    "attr_flex":null,
    "attr_balance":null,
    "_attr_tempo":null,
    "difficulty":null,
    "node_heated":null,
    "node_injuries":"",
    "node_stand":"",
    "node_meditation":"",
    "node_chanting":"",
    "node_core":"",
    "node_spirit":"",
    "node_beginner":"",
    "class_description":"",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Soul Shine Yoga",
    "class_id":15,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"jennifer",
    "teacher_name":"Jennifer",
    "class_start":"10:00 AM",
    "class_end":"11:15 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":6,
    "attr_flex":8,
    "attr_balance":5,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Get your groove on and energize for the day with Soul Shine Yoga, a class that integrates Hatha and a Kundalini blend of energizing postures linked with a connective movement of Vinyasa. This class is aimed to bring positive vibrations into your life, by using tools and techniques including sun salutations, hatha asana sequences, restorative postures, yogic breathing exercises, mantra, creative movement, meditation and inspirational quotes from yogic mystics.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":16,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"12:00 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":8,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"In this breath centered, core strengthening vinyasa flow class students will be given the space and support to safely deepen their practice. Focusing on organic, intuitive movement, biomechanical alignment and powerful pranayama techniques, this class will help students strengthen and transform their practice on and off the mat. All levels and practices welcome.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"FREQUENCYasa Yoga",
    "class_id":19,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Asha",
    "class_start":"12:15 PM",
    "class_end":"1:30 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":6,
    "_attr_tempo":5,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Vinyasa Basics, blending Vinyasa flow with Alignment, experience the body in its element! Breathe, Body and Mind in Union. We will break down the Asana’s (poses) and flow through the basics of Yoga with Grace and Ease.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Power Vinyasa Yoga ",
    "class_id":20,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Yoni",
    "class_start":"3:30 PM",
    "class_end":"4:45 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Yoni Berk teaches a strong vinyasa flow class designed to build a complete and solid yogic practice. With a focus on the breathe, attention to alignment, and creative sequencing, Yoni will guide you through understanding the dynamics of a strong vinyasa flow. Fusing introspective focus and light heartedness, learn to ease the mind through challenging the body. With a background in music, Yoni’s unique playlists are a draw for many student. Come for the yoga, stay for the music.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Yoga Flow",
    "class_id":21,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"jennifer",
    "teacher_name":"Jennifer",
    "class_start":"3:45 PM",
    "class_end":"5:00 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":6,
    "_attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Journey into the depths of your mystical heart, with a unique blend of Hatha and Kundalini yoga, designed to assist you in touching the untouchable~ your soul essence. This class works with a range of yogic tools from asana (posture) pranayama (breathing), mantras (chanting), meditation and insight from wisdom passed down from the yoga sutras of Patanjali.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Prana Flow",
    "class_id":22,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Pixie",
    "teacher_name":"Pixie",
    "class_start":"5:00 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":8,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Prana Flow is an energetic, creative, full-spectrum approach to embodying the flow of yoga cultivated by Shiva Rea and the Global Vinyasa Collective of Teachers. Students of all levels are empowered to experience prana – the universal source of breath, life energy and conscious intelligence – as the navigating source of yoga practice and vital living. Practitioners learn classical and innovative approaches to vinyasa yoga and the state of flow drawn from Krishnamacharya’s teachings, Tantra, Ayurveda, Bhakti, Somatics and Shiva’s teaching experience from the last fifteen years.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Restorative & Yin Yoga",
    "class_id":23,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"deborah",
    "teacher_name":"Deborah",
    "class_start":"5:15 PM",
    "class_end":"6:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":1,
    "attr_flex":6,
    "attr_balance":3,
    "_attr_tempo":1,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"A deeply calming practice of sustained and supported poses to open the body, gently release tension in the connective tissues, bring us into the moment, and heighten awareness of our true essence. Nourish and restore while settling the mind and enlivening the Spirit. All are welcome.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Power Vinyasa Level 2/3",
    "class_id":24,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":10,
    "attr_flex":10,
    "attr_balance":10,
    "_attr_tempo":10,
    "difficulty":2,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Build strength and create balance inside and out. Nuria challenges students with a creative vivacious sequence and challenging poses.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":25,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_start":"6:45 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":8,
    "attr_flex":6,
    "attr_balance":8,
    "_attr_tempo":10,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students and modifications for newer students. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm.",
    "node_music":1,
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Metacine Sound Bath",
    "class_id":null,
    "studio_id":null,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Shane",
    "teacher_name":"Shane",
    "class_start":"8:15 PM",
    "class_end":"9:45 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":0,
    "attr_flex":0,
    "attr_balance":null,
    "_attr_tempo":0,
    "difficulty":null,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Come and enjoy a restorative vibrational experience with the crystal quartz singingCome and enjoy a restorative galactivation vibrational experience with the crystal + tibetan singing bowls, cosmic chimes, crystal pyramids, aromatherapy, and guided meditation. Utilizing 99.9% pure tonal frequency of our chakras and the 432hz harmonic of light, this sound bath will cleanse and purge emotional, mental, physical, and spiritual blockages while re-tuning & calibrating dimensional frequencies for healing and balance. As the chakras are cleansed and purified of any imbalanced energies, a blissful, transforming and uplifting experience awaits the mind, body, emotions and spirit. Students will feel more grounded, aligned, and balanced for their life experience! All creeds, paths, vibrations, and frequencies are welcome. Blessings!",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Kundalini",
    "class_id":26,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Jordan",
    "class_start":"8:30 PM",
    "class_end":"9:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":5,
    "attr_flex":6,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":27,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_start":"6:30 AM",
    "class_end":"7:30 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":8,
    "attr_flex":6,
    "attr_balance":8,
    "_attr_tempo":10,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Vinyasa flow links breath with movement. Tiff's classes are challenging, but with teired levels so all can participate. Be ready to sweat!",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Pilates Yoga Fusion",
    "class_id":28,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Arianna",
    "class_start":"8:00 AM",
    "class_end":"9:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":10,
    "attr_flex":5,
    "attr_balance":7,
    "_attr_tempo":10,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"A energetic balance between core/stabilization focused vinyasa flows and Pilates core conditioning on the mat. Expect a hot room of 85-90 degrees, groovy tunes, and a rewarding challenge.",
    "node_music":1,
    "short_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students and modifications for newer students. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm.",
    "unique_pitch":"I break tradition by adding pulsation, funky flow sequences, and different rhythm of breathing, all paired with energetic jazzy music!"
  },
  {
    "class_name":"AyurYoga Flow",
    "class_id":29,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Kellen",
    "teacher_name":"Kellen",
    "class_start":"9:15 AM",
    "class_end":"10:30 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":5,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Weaving the healing principles of Ayurveda with the graceful flow of Vinyasa Yoga, Kellen's classes cultivate strength and flexibility in the body, and inspire peace in the mind. ",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Prana Flow ",
    "class_id":30,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Pixie",
    "teacher_name":"Pixie",
    "class_start":"9:30 AM",
    "class_end":"11:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":8,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Prana Flow is an energetic, creative, full-spectrum approach to embodying the flow of yoga cultivated by Shiva Rea and the Global Vinyasa Collective of Teachers. Students of all levels are empowered to experience prana – the universal source of breath, life energy and conscious intelligence – as the navigating source of yoga practice and vital living. Practitioners learn classical and innovative approaches to vinyasa yoga and the state of flow drawn from Krishnamacharya’s teachings, Tantra, Ayurveda, Bhakti, Somatics and Shiva’s teaching experience from the last fifteen years.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Power Vinyasa",
    "class_id":31,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Nuria",
    "class_start":"12:00 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":8,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Yoga",
    "class_id":32,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_start":"12:15 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":4,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"yo•ga | ˈyōgə | unión | • Asana ~ postures • Pranayama ~ breath control • Mantra ~ sound • Meditation ~ stillness Experience balance and peace in this hour long class. Focus your attention inward while we will take the traditional practice of yoga into a modern design, tailored to our community. Each day will be different. Whether you come once a month or three times a week, It will be well rounded and include a theme that rotates weekly to include all aspects of yoga, physical and non-physical, each month. Join in this sweet practice, honoring the full spectrum of life and ourselves.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Yoga Schmoga ~ Community Class",
    "class_id":33,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Patrick",
    "class_start":"3:30 PM",
    "class_end":"4:45 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":3,
    "attr_flex":6,
    "attr_balance":7,
    "_attr_tempo":4,
    "difficulty":1,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Mindful movement and breath. Yoga for everybody. ~ This is a community class and available by donation.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Strong Flow",
    "class_id":35,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_start":"5:15 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":6,
    "_attr_tempo":7,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Chyla’s class will challenge you to push your edge while reminding you to stay soft and open. Expect a fun yet strong practice with soulful connection and her latest fresh playlist!",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Power Flow ",
    "class_id":36,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"sarah",
    "teacher_name":"Sarah",
    "class_start":"5:15 PM",
    "class_end":"6:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":2,
    "attr_strength":7,
    "attr_flex":8,
    "attr_balance":6,
    "_attr_tempo":8,
    "difficulty":null,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Slow down and re-charge with an empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students and modifications for newer students. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Leave class inspired, peaceful & energized.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Power Vinyasa Level 2/3",
    "class_id":38,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":10,
    "attr_flex":9,
    "attr_balance":10,
    "_attr_tempo":9,
    "difficulty":3,
    "node_heated":10,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students including vigorous sequences and advanced postures. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Heated to enhance flexibility and endurance. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Restorative Yoga",
    "class_id":39,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Bettina",
    "class_start":"6:45 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":3,
    "attr_flex":2,
    "attr_balance":1,
    "_attr_tempo":1,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":0,
    "node_beginner":1,
    "class_description":"Renew your energy. Rest, breathe & be. Learn to heal yourself. A class designed for deep release, expansion & freedom. Sequences coreographed to open & heal the body, soul & mind. Work with your breath & awareness to create a radical Sequences coreographed to open & heal the body, soul & mind. Work with your breath & awareness to create a radical shift in your being.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Partner Yoga & Flying",
    "class_id":40,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Arianna",
    "class_start":"8:15 PM",
    "class_end":"9:40 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":10,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":0,
    "node_beginner":1,
    "class_description":"AcroYoga is a playful form of partner yoga that also incorporates acrobatics and Thai Massage. Expect a fun, energetic environment, groovy music, and to leave feeling challenged and excited! No partner or experience is necessary. Donations of $5+ suggested. ",
    "node_music":"",
    "short_description":"AcroYoga is a playful form of partner yoga that also incorporates acrobatics and Thai Massage. Expect a fun, energetic environment, groovy music, and to leave feeling challenged and excited! No partner or experience is necessary. Donations of $5+ suggested. ",
    "unique_pitch":"I enjoy challenging the students, while keeping the energy light and fun. My love for acrobatics, yoga, and teaching get to collide to funky tunes! "
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":41,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Bettina",
    "class_start":"6:30 AM",
    "class_end":"7:35 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":null,
    "_attr_tempo":7,
    "difficulty":null,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Options offered within the practice for beginning to advanced practitioners. Come ready to breath, sweat, and open up! ",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Strong Flow",
    "class_id":42,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Chyla",
    "class_start":"8:00 AM",
    "class_end":"9:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":5,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Chyla’s class will challenge you to push your edge while reminding you to stay soft and open. Expect a fun yet strong practice with soulful connection and her latest fresh playlist!",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Kundalini Yoga",
    "class_id":43,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Vikki",
    "teacher_name":"Vikki",
    "class_start":"8:30 AM",
    "class_end":"9:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":null,
    "attr_flex":null,
    "attr_balance":null,
    "_attr_tempo":null,
    "difficulty":null,
    "node_heated":null,
    "node_injuries":"",
    "node_stand":"",
    "node_meditation":"",
    "node_chanting":"",
    "node_core":"",
    "node_spirit":"",
    "node_beginner":"",
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Pilates-Yoga Fusion, Hot Level 2",
    "class_id":44,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Arianna",
    "class_start":"9:30 AM",
    "class_end":"10:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":10,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":10,
    "difficulty":2,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"A energetic balance between core/stabilization focused vinyasa flows and Pilates core conditioning on the mat. Expect a hot room of 85-90 degrees, groovy tunes, and a rewarding challenge.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":45,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"12:00 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"FREQUENCYasa Yoga",
    "class_id":46,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Asha",
    "class_start":"12:15 PM",
    "class_end":"1:30 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":7,
    "difficulty":1,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Vinyasa Basics, blending Vinyasa flow with Alignment, experience the body in its element! Breathe, Body and Mind in Union. We will break down the Asana’s (poses) and flow through the basics of Yoga with Grace and Ease.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Power Vinyasa ",
    "class_id":47,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Yoni",
    "class_start":"3:30 PM",
    "class_end":"4:45 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Yoni Berk teaches a strong vinyasa flow class designed to build a complete and solid yogic practice. With a focus on the breathe, attention to alignment, and creative sequencing, Yoni will guide you through understanding the dynamics of a strong vinyasa flow. Fusing introspective focus and light heartedness, learn to ease the mind through challenging the body. With a background in music, Yoni’s unique playlists are a draw for many student. Come for the yoga, stay for the music.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Power Vinyasa Level 2/3",
    "class_id":48,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_start":"5:00 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":10,
    "attr_flex":10,
    "attr_balance":10,
    "_attr_tempo":10,
    "difficulty":2,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Build strength and create balance inside and out. Nuria challenges students with a creative vivacious sequence and challenging poses.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":49,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_start":"5:15 PM",
    "class_end":"6:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":8,
    "attr_flex":6,
    "attr_balance":8,
    "_attr_tempo":10,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Vinyasa flow links breath with movement. Tiff's classes are challenging, but with teired levels so all can participate. Be ready to sweat!",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Prana Flow",
    "class_id":50,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Pixie",
    "teacher_name":"Pixie",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":8,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Prana Flow is an energetic, creative, full-spectrum approach to embodying the flow of yoga cultivated by Shiva Rea and the Global Vinyasa Collective of Teachers. Students of all levels are empowered to experience prana – the universal source of breath, life energy and conscious intelligence – as the navigating source of yoga practice and vital living. Practitioners learn classical and innovative approaches to vinyasa yoga and the state of flow drawn from Krishnamacharya’s teachings, Tantra, Ayurveda, Bhakti, Somatics and Shiva’s teaching experience from the last fifteen years.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Yin Restorative Yoga with Crystal Bowls",
    "class_id":51,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Amanda",
    "teacher_name":"Amanda",
    "class_start":"6:45 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":3,
    "attr_flex":3,
    "attr_balance":3,
    "_attr_tempo":3,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":0,
    "node_beginner":1,
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Intro to Contact Improvisation",
    "class_id":null,
    "studio_id":null,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Jenna",
    "teacher_name":"Jenna",
    "class_start":"8:15 PM",
    "class_end":"9:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":5,
    "attr_flex":5,
    "attr_balance":null,
    "_attr_tempo":5,
    "difficulty":null,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Contact Improvisation is a revolution: an opportunity to follow bodily sensations in a mutually dependent dialogue of weight-bearing, a discovery of the mystery of movement through non-doing. Postmodern and genre-defying, CI is based on a rolling point of physical contact between dancers who yield to each other’s bodies to create a fluid exchange of weight. In this class, we will expand upon improvisation as a metaphor for life: exploring movement as a vehicle for expression and a means for engaging spontaneously and creatively with our surroundings. The class will incorporate a variety of performance techniques including voice and theatre, Somatics and breath work, authentic movement, and jamming in order to celebrate the mind-body connection and hone our instruments as human beings. Open to dancers, actors, writers, artists, yogis, and musicians of all abilities and ages! No previous dance experience required. ",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":52,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Bettina",
    "class_start":"6:30 AM",
    "class_end":"7:30 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":null,
    "_attr_tempo":7,
    "difficulty":null,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Options offered within the practice for beginning to advanced practitioners. Come ready to breath, sweat, and open up! ",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Good Morning Power Flow",
    "class_id":53,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Aliza",
    "teacher_name":"Aliza",
    "class_start":"8:00 AM",
    "class_end":"9:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":7,
    "attr_flex":5,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Come get your ya-yas out, bridge the gap between the arts in Santa Barbara, and explore a new way of moving through the world!",
    "node_music":1,
    "short_description":"My class is a combination of holding poses - breaking down the alignment and placement of the body with vinyasa flow - connecting breath to movement. I always end class with some nice, juicy restorative poses as well. ",
    "unique_pitch":"I think my class is the best of both worlds. Holding poses to build strength and cultivate attention and flowing through poses to bring awareness to the breath and body. My goal is to help students find moments of stillness in the mind, moments of meditation in the flow. "
  },
  {
    "class_name":"Strong Flow",
    "class_id":54,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_start":"9:30 AM",
    "class_end":"10:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":5,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Chyla’s class will challenge you to push your edge while reminding you to stay soft and open. Expect a fun yet strong practice with soulful connection and her latest fresh playlist!",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Vinyasa/Medical Chi Gong",
    "class_id":55,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_start":"10:30 AM",
    "class_end":"11:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":6,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"“The dream of first principles is alive when boundaries are transgressed, and life emerges as movement in itself.” – Petra Kuppers",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"California Flow",
    "class_id":56,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_start":"12:00 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":8,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Yoga ",
    "class_id":57,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_start":"12:15 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"yo•ga | ˈyōgə | unión | • Asana ~ postures • Pranayama ~ breath control • Mantra ~ sound • Meditation ~ stillness Experience balance and peace in this hour long class. Focus your attention inward while we will take the traditional practice of yoga into a modern design, tailored to our community. Each day will be different. Whether you come once a month or three times a week, It will be well rounded and include a theme that rotates weekly to include all aspects of yoga, physical and non-physical, each month. Join in this sweet practice, honoring the full spectrum of life and ourselves.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":58,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Rachel Meisler",
    "class_start":"3:30 PM",
    "class_end":"4:45 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Power Vinyasa",
    "class_id":59,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"candice",
    "teacher_name":"Candice",
    "class_start":"5:00 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "_attr_tempo":8,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"“Sweating is meditating!” In Power Vinyasa, incorporates a fitness centered approach to yoga that focuses on maximizing the human body’s potential. Each class will be designed to synchronize breath with a series of poses. Advanced poses will be offered, but modifications will always be available. This class is meant to create the strength and flexibility that is essential for injury prevention and overall wellness. This is a great class for athletes and for those looking to improve their fitness level. Be prepared for a heated, fun, high energy vinyasa flow with movement-inspiring beats from around the world.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Kundalini Yoga",
    "class_id":60,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Mitsuko",
    "class_start":"5:15 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":5,
    "attr_flex":5,
    "attr_balance":3,
    "_attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Sat Nam.",
    "node_music":1,
    "short_description":"With this practice the practitioner will be able to change and break habits to support their innate potential.  With regular practice in this class the practitioner will build physical, mental, emotional and spiritual self discipline which will support an increased sense of inner peace and calm, stress and anxiety relief, an increased level of energy and productivity by performing a series of repeated physical exercises for an uninterrupted period of time while: holding specific hand postitions, maintaining a specific eye focus, verbally and/or mentally chanting a mantra and sustaining a specified breathing pattern.",
    "unique_pitch":"My goal is to support students on a path of doing a daily yoga practice by, each month, focusing on a specific sequence of exercises in class to build muscle memory to support self discovery. "
  },
  {
    "class_name":"Breathing, Stretching, Relaxing: A community class.",
    "class_id":61,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"deborah",
    "teacher_name":"Deborah",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":1,
    "attr_flex":6,
    "attr_balance":3,
    "_attr_tempo":1,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Breathing, Stretching, Relaxing: A community class.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Morning Practice",
    "class_id":62,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Siddhi",
    "class_start":"9:15 AM",
    "class_end":"10:30 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":1,
    "day_6":0,
    "class_day":5,
    "attr_strength":3,
    "attr_flex":0,
    "attr_balance":0,
    "_attr_tempo":3,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"The morning practice provides a space in which every student can deepen their connection with themselves.Our morning practice will always be different in content, reflecting the consistent change with life.This class has been structured for internal expansion, liberation from restrictions as well as a powerful connection to the divine essence that surrounds us all.All levels are welcomed, everyone will benefit from taking part.The practice is based on Kundalini, Naam and Sattva Yoga.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Power Vinyasa Level 2/3",
    "class_id":63,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"9:30 AM",
    "class_end":"11:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":1,
    "day_6":0,
    "class_day":5,
    "attr_strength":10,
    "attr_flex":10,
    "attr_balance":9,
    "_attr_tempo":9,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"A well rounded class of simple breathing exercises, deep and gentle stretches, movement and a final deep relaxation. This class is designed to alleviate the stress of modern life on the body, mind and spirit. Suitable for all levels. Available as a donation class for those who can’t afford our regular rates",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Slow Flow",
    "class_id":64,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Bettina",
    "class_start":"11:00 AM",
    "class_end":"12:15 AM",
    "node_morning":1,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":1,
    "day_6":0,
    "class_day":5,
    "attr_strength":3,
    "attr_flex":3,
    "attr_balance":null,
    "_attr_tempo":3,
    "difficulty":null,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Vinyasa Basics, blending Vinyasa flow with Alignment, experience the body in its element! Breathe, Body and Mind in Union. We will break down the Asana’s (poses) and flow through the basics of Yoga with Grace and Ease.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Strong Flow",
    "class_id":65,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_start":"11:30 AM",
    "class_end":"12:45 PM",
    "node_morning":1,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":1,
    "day_6":0,
    "class_day":5,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":6,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Chyla’s class will challenge you to push your edge while reminding you to stay soft and open. Expect a fun yet strong practice with soulful connection and her latest fresh playlist!",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Liquid Flow with Live Music",
    "class_id":66,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Amanda",
    "class_start":"4:30 PM",
    "class_end":"6:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":1,
    "day_6":0,
    "class_day":5,
    "attr_strength":null,
    "attr_flex":null,
    "attr_balance":null,
    "_attr_tempo":null,
    "difficulty":null,
    "node_heated":null,
    "node_injuries":"",
    "node_stand":"",
    "node_meditation":"",
    "node_chanting":"",
    "node_core":"",
    "node_spirit":"",
    "node_beginner":"",
    "class_description":"",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Community Meditation",
    "class_id":67,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Karen Gabai",
    "class_start":"9:00 AM",
    "class_end":"9:30 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":0,
    "attr_flex":0,
    "attr_balance":null,
    "_attr_tempo":0,
    "difficulty":null,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Some benefits to cultivating a regular meditation practice include: reduced stress, increased productivity, better focus, greater creativity, increased immunity, better memory, and a greater sense of overall being. ",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Kundalini Yoga",
    "class_id":68,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Kirtan",
    "class_start":"9:30 AM",
    "class_end":"10:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":5,
    "attr_flex":6,
    "attr_balance":5,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Sunday Practice w/ Live Music",
    "class_id":69,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_start":"11:00 AM",
    "class_end":"12:15 PM",
    "node_morning":1,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Restorative & Yin Yoga",
    "class_id":null,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Jenn",
    "class_start":"11:15 AM",
    "class_end":"12:30 PM",
    "node_morning":1,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":0,
    "attr_flex":1,
    "attr_balance":null,
    "_attr_tempo":1,
    "difficulty":null,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"A deeply calming practice of sustained and supported poses to open the body. Jenn guides you to connect to your body and always has yummy essential oils! ",
    "node_music":1,
    "short_description":"You will move through gentle, restorative poses using supports of yoga props allowing your nervous system to relax.  Yin poses will stretch the connective tissue, giving your muscles permission to surrender to gravity.",
    "unique_pitch":"I love to guide you to connect to your body with directing your breath, sensation, and gratitude for this amazing life force from within.  I also love beautiful yoga music and essential oils!"
  },
  {
    "class_name":"Vinyasa Basics",
    "class_id":70,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Amanda",
    "class_start":"1:00 PM",
    "class_end":"2:30 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Vinyasa Basics, blending Flow with Alignment, experience the body in its element! Breath, Body and Mind in Union. We will break down the Asana’s (poses) and flow through the basics of Yoga with Grace and Ease. Classes are joyous and infused with a sense of play. Good for experienced students and beginners alike who are looking for a deeper understanding of the poses in your body and connection of breath with movement.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Metacine Sound Bath",
    "class_id":71,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Asha & Sean",
    "class_start":"1:15 PM",
    "class_end":"3:30 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":null,
    "attr_flex":null,
    "attr_balance":null,
    "_attr_tempo":null,
    "difficulty":null,
    "node_heated":null,
    "node_injuries":"",
    "node_stand":"",
    "node_meditation":"",
    "node_chanting":"",
    "node_core":"",
    "node_spirit":"",
    "node_beginner":"",
    "class_description":"Come and enjoy a restorative vibrational experience with the crystal quartz singingCome and enjoy a restorative galactivation vibrational experience with the crystal + tibetan singing bowls, cosmic chimes, crystal pyramids, aromatherapy, and guided meditation. Utilizing 99.9% pure tonal frequency of our chakras and the 432hz harmonic of light, this sound bath will cleanse and purge emotional, mental, physical, and spiritual blockages while re-tuning & calibrating dimensional frequencies for healing and balance. As the chakras are cleansed and purified of any imbalanced energies, a blissful, transforming and uplifting experience awaits the mind, body, emotions and spirit. Students will feel more grounded, aligned, and balanced for their life experience! All creeds, paths, vibrations, and frequencies are welcome. Blessings!",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Eclectic Flow",
    "class_id":72,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Brett",
    "teacher_name":"Brett",
    "class_start":"5:00 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":7,
    "_attr_tempo":6,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"A strong mix of ashtanga, bikram, and iyengar poses with pranayama. Temp 87degrees.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Kirtan and Sacred Music",
    "class_id":73,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Jacob",
    "class_start":"6:00 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":0,
    "attr_flex":0,
    "attr_balance":0,
    "_attr_tempo":0,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"COMMUNITY EVENT EVERY 7! Devotional singing guides us into incredible states of meditation and bliss. Ancient sanskrit mantras are rendered into traditional melodies and accompanied by shamanic drum beats. The kirtan leader sings the call and the audience sings the response for a truly interactive musical experience where an entire room of people create healing intentions and positive expressions. The focus of the chants are Hindu deities – symbols of the ideal intentions we wish to bring into our lives. This beautiful practice is recognized in the yoga community as the quickest path to bliss, harmony and enlightenment.Suggested $15-20 Love Donation",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  },
  {
    "class_name":"Vinyasa Flow - Community Class ",
    "class_id":74,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "_attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"In this breath centered, core strengthening vinyasa flow class students will be given the space and support to safely deepen their practice. Breath, sweat, play and donate what you can. All levels and practices welcome.",
    "node_music":"",
    "short_description":"",
    "unique_pitch":""
  }
];