window.classes = [
  {
    "class_name":"Vinyasa ",
    "class_id":345,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_start":"6:00 AM",
    "class_end":"7:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":7,
    "attr_flex":8,
    "attr_balance":8,
    "attr_tempo":10,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Advanced Yoga",
    "class_id":346,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Jasha",
    "teacher_name":"Jasha",
    "class_start":"9:30 AM",
    "class_end":"11:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":9,
    "attr_flex":8,
    "attr_balance":10,
    "attr_tempo":6,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Advanced Yoga:\nFrom the traditional roots of yoga this advanced class is designed to take your yoga practice deeper. \n\nStrengthen your body using movement, find peace using meditation and invite transformation using breath work and sound. You will be carefully guided to find new ways to approach familiar postures as well as exploring new ones in a playful way.\n\nFind out why yoga is more than just a workout by finding beauty within each breath.",
    "node_music":""
  },
  {
    "class_name":"Kundalini ",
    "class_id":347,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Kirtan",
    "class_start":"10:45 AM",
    "class_end":"12:00 PM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":5,
    "attr_flex":6,
    "attr_balance":5,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam.",
    "node_music":""
  },
  {
    "class_name":"Lunch Break Power Flow",
    "class_id":348,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Sarah",
    "teacher_name":"Sarah",
    "class_start":"12:00 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":7,
    "attr_flex":8,
    "attr_balance":6,
    "attr_tempo":8,
    "difficulty":2,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"A mid-day pick-me-up. Slow down and re-charge with an empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students and modifications for newer students. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Leave class inspired, peaceful & energized.",
    "node_music":""
  },
  {
    "class_name":"Yoga ",
    "class_id":349,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Jasha",
    "teacher_name":"Jasha",
    "class_start":"12:15 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Experience balance and peace in this hour long class. Focus your attention inward while we will take the traditional practice of yoga into a modern design, tailored to our community. Each day will be different. Whether you come once a month or three times a week, It will be well rounded and include a theme that rotates weekly to include all aspects of yoga, physical and non-physical, each month. Join in this sweet practice, honoring the full spectrum of life and ourselves.",
    "node_music":""
  },
  {
    "class_name":"Liquid Flow w/ Sacred Sound",
    "class_id":351,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Amanda",
    "class_start":"3:30 PM",
    "class_end":"4:45 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":7,
    "attr_flex":8,
    "attr_balance":8,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"A multi-level class designed for new and experienced students. There will be progressive options offered in many asanas so that each person will be challenged at their level. A variety of new asanas will be practiced each class to explore and build upon your current practice. Expect a dynamic class which is a creative blend, emphasizing the union of breath, body, and mind. Classes are joyous and infused with a sense of play.",
    "node_music":""
  },
  {
    "class_name":"All Levels Power Vinyasa Yoga",
    "class_id":352,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"candice",
    "teacher_name":"Candice",
    "class_start":"5:00 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "attr_tempo":8,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":353,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Aliza",
    "teacher_name":"Aliza",
    "class_start":"5:15 PM",
    "class_end":"6:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":5,
    "attr_flex":5,
    "attr_balance":5,
    "attr_tempo":5,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students and modifications for newer students. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm.",
    "node_music":""
  },
  {
    "class_name":"Power Vinyasa Level 2/3 ",
    "class_id":354,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":10,
    "attr_flex":10,
    "attr_balance":9,
    "attr_tempo":9,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students including vigorous sequences and advanced postures. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Heated to enhance flexibility and endurance. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Restorative Kundalini Yoga and Meditation",
    "class_id":355,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Vikki",
    "teacher_name":"Vikki",
    "class_start":"6:45 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":1,
    "attr_flex":7,
    "attr_balance":2,
    "attr_tempo":1,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Turn Your 1 BLAH’S into 1 AHH’sMore than just a set of physical exercises, Kundalini Yoga is a science and technology designed to heal at the very core. In each Kundalini yoga class we use a powerful combination of postures, breath, sound, meditation, and relaxation to strengthen the body, calm the mind and awaken the spirit. In this restorative class, we begin with calming breath to quiet the mind and soothe the nervous system. Moving into a gentle posture sequence, we synchronize our breath and movement, dissolving the deeply held tension in the body. As the energy begins to move, we find greater balance as we reconnect to our center. From this open and relaxed space, we flow into extended mantra and meditation, followed by a deep relaxation. Body, mind and spirit will be touched, loved and deeply nourished. No prior yoga experience is necessary. Class is suitable for all levels and ages.",
    "node_music":""
  },
  {
    "class_name":"Intro to Contact Improvisation",
    "class_id":356,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Jenna",
    "class_start":"8:15 PM",
    "class_end":"9:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":6,
    "attr_tempo":9,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Contact Improvisation is a revolution: an opportunity to follow bodily sensations in a mutually dependent dialogue of weight-bearing, a discovery of the mystery of movement through non-doing. Postmodern and genre-defying, CI is based on a rolling point of physical contact between dancers who yield to each other’s bodies to create a fluid exchange of weight. In this class, we will expand upon improvisation as a metaphor for life: exploring movement as a vehicle for expression and a means for engaging spontaneously and creatively with our surroundings. The class will incorporate a variety of performance techniques including voice and theatre, Somatics and breath work, authentic movement, and jamming in order to celebrate the mind-body connection and hone our instruments as human beings. Open to dancers, actors, writers, artists, yogis, and musicians of all abilities and ages! No previous dance experience required. ",
    "node_music":""
  },
  {
    "class_name":"Goddess Circle",
    "class_id":358,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Amanda",
    "class_start":"8:30 PM",
    "class_end":"9:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":1,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":0,
    "attr_strength":5,
    "attr_flex":6,
    "attr_balance":6,
    "attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"We start with a little bit of yoga and open up into group meditation creating a safe space to explore, support, grow and thrive.",
    "node_music":""
  },
  {
    "class_name":"Vinyasa",
    "class_id":359,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_start":"6:30 AM",
    "class_end":"7:05 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":5,
    "attr_tempo":5,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Soul Shine Yoga",
    "class_id":360,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"jennifer",
    "teacher_name":"Jennifer",
    "class_start":"8:00 AM",
    "class_end":"9:15 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":6,
    "attr_flex":8,
    "attr_balance":5,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Get your groove on and energize for the day with Soul Shine Yoga, a class that integrates Hatha and a Kundalini blend of energizing postures linked with a connective movement of Vinyasa. This class is aimed to bring positive vibrations into your life, by using tools and techniques including sun salutations, hatha asana sequences, restorative postures, yogic breathing exercises, mantra, creative movement, meditation and inspirational quotes from yogic mystics.",
    "node_music":""
  },
  {
    "class_name":"Yoga and Meditation",
    "class_id":361,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Peggy",
    "class_start":"9:15 AM",
    "class_end":"10:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":3,
    "attr_flex":8,
    "attr_balance":3,
    "attr_tempo":3,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"This class explores both the physical power and transformative potential of yoga, and encourages students to develop mindfulness, confidence, and compassion through an emphasis on the breath and body alignment. It is suitable for yogis of any level of experience. Modifications to poses are offered throughout, allowing students to benefit from every pose. Each class is designed to open and strengthen even the most resistant bodies, and the supportive and compassionate environment, with an emphasis on alignment, allows students to work towards their personal edge without fear of injury. In Yoga and Meditation, students work with asana, pranayama and meditation to experience the power of yoga. Come see how this power affects our lives both on and off the mat.",
    "node_music":""
  },
  {
    "class_name":"Cardio Dance",
    "class_id":362,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Briana",
    "teacher_name":"Briana",
    "class_start":"9:30 AM",
    "class_end":"11:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":8,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"",
    "node_music":""
  },
  {
    "class_name":"All Levels Power Vinyasa Yoga ",
    "class_id":363,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"12:00 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Vinyasa Basics",
    "class_id":364,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Asha",
    "class_start":"12:15 PM",
    "class_end":"1:30 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":6,
    "attr_tempo":5,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Vinyasa Basics, blending Vinyasa flow with Alignment, experience the body in its element! Breathe, Body and Mind in Union. We will break down the Asana’s (poses) and flow through the basics of Yoga with Grace and Ease.",
    "node_music":""
  },
  {
    "class_name":"Acu-Intuitive Flow",
    "class_id":365,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_start":"2:15 PM",
    "class_end":"3:30 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":6,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Rachel blends a combination of Vinyasa flow, energy movement, breathing, meditation and deep relaxation. The movements are gentle, yet still challenging, and they work to activate life force, release stress and promote better circulation, self-awareness and inner peace.",
    "node_music":""
  },
  {
    "class_name":"Power Vinyasa",
    "class_id":366,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Yoni",
    "class_start":"3:30 PM",
    "class_end":"4:45 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Yoni Berk teaches a strong vinyasa flow class designed to build a complete and solid yogic practice. With a focus on the breathe, attention to alignment, and creative sequencing, Yoni will guide you through understanding the dynamics of a strong vinyasa flow. Fusing introspective focus and light heartedness, learn to ease the mind through challenging the body. With a background in music, Yoni’s unique playlists are a draw for many student. Come for the yoga, stay for the music.",
    "node_music":""
  },
  {
    "class_name":"Yoga Flow",
    "class_id":367,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"jennifer",
    "teacher_name":"Jennifer",
    "class_start":"3:45 PM",
    "class_end":"5:00 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":6,
    "attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Journey into the depths of your mystical heart, with a unique blend of Hatha and Kundalini yoga, designed to assist you in touching the untouchable~ your soul essence. This class works with a range of yogic tools from asana (posture) pranayama (breathing), mantras (chanting), meditation and insight from wisdom passed down from the yoga sutras of Patanjali.",
    "node_music":""
  },
  {
    "class_name":"Prana Flow",
    "class_id":368,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Pixie",
    "teacher_name":"Pixie",
    "class_start":"5:00 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":8,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Prana Flow is an energetic, creative, full-spectrum approach to embodying the flow of yoga cultivated by Shiva Rea and the Global Vinyasa Collective of Teachers. Students of all levels are empowered to experience prana – the universal source of breath, life energy and conscious intelligence – as the navigating source of yoga practice and vital living. Practitioners learn classical and innovative approaches to vinyasa yoga and the state of flow drawn from Krishnamacharya’s teachings, Tantra, Ayurveda, Bhakti, Somatics and Shiva’s teaching experience from the last fifteen years.",
    "node_music":""
  },
  {
    "class_name":"Restorative & Yin Yoga",
    "class_id":369,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"deborah",
    "teacher_name":"Deborah",
    "class_start":"5:15 PM",
    "class_end":"6:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":1,
    "attr_flex":6,
    "attr_balance":3,
    "attr_tempo":1,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"A deeply calming practice of sustained and supported poses to open the body, gently release tension in the connective tissues, bring us into the moment, and heighten awareness of our true essence. Nourish and restore while settling the mind and enlivening the Spirit. All are welcome.",
    "node_music":""
  },
  {
    "class_name":"Power Vinyasa Level 2/3",
    "class_id":370,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":10,
    "attr_flex":10,
    "attr_balance":10,
    "attr_tempo":10,
    "difficulty":2,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students including vigorous sequences and advanced postures. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Heated to enhance flexibility and endurance. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":371,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_start":"6:45 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":7,
    "attr_flex":8,
    "attr_balance":8,
    "attr_tempo":10,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students and modifications for newer students. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm.",
    "node_music":""
  },
  {
    "class_name":"Eclectic Yin Yang",
    "class_id":372,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_start":"8:15 PM",
    "class_end":"9:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":6,
    "attr_flex":7,
    "attr_balance":4,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"A fusion of Hatha, Vinyasa, Iyengar and Yin yoga with the last half hour spent in restorative poses. Calming, deepening and nourishing.",
    "node_music":""
  },
  {
    "class_name":"Kundalini",
    "class_id":373,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_start":"8:30 PM",
    "class_end":"9:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":1,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":1,
    "attr_strength":5,
    "attr_flex":6,
    "attr_balance":5,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam.",
    "node_music":""
  },
  {
    "class_name":"Vinyasa",
    "class_id":374,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_start":"6:00 AM",
    "class_end":"7:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":7,
    "attr_flex":8,
    "attr_balance":8,
    "attr_tempo":10,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Kundalini ",
    "class_id":375,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Vikki",
    "teacher_name":"Vikki",
    "class_start":"7:45 AM",
    "class_end":"9:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":5,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam.",
    "node_music":""
  },
  {
    "class_name":"Pilates-Yoga Fusion, All Levels ",
    "class_id":376,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Arianna",
    "class_start":"8:00 AM",
    "class_end":"9:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Strengthen core muscles; improve coordination, balance, and posture, gain tone, grace, and flexibility. Breathe deeply; release tension; develop profound awareness and mind-body connection. You will feel and function better all-around! Class includes: options for working and different levels so you meet your body’s ever changing needs; precise alignment descriptions + creative visualizations so you move safely, effectively, with joy and humor; varied sequencing so you are thoroughly engaged from head to toe; and a restorative cool-down and deeply delicious relaxation, so you finish fully refreshed and energized. All levels welcome!",
    "node_music":""
  },
  {
    "class_name":"AyurYoga Flow",
    "class_id":377,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Kellen",
    "teacher_name":"Kellen",
    "class_start":"9:15 AM",
    "class_end":"10:30 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":5,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Weaving the healing principles of Ayurveda with the graceful flow of Vinyasa Yoga, Kellen’s AyurYoga classes cultivate strength and flexibility in the body, and inspire peace in the mind. Classes explore the relationship of the poses with the 5 elements, 3 doshas, breath, and Ayurvedic acupressure points. Enjoy balance in the body, mind and senses when you bring your doshas hOMe.",
    "node_music":""
  },
  {
    "class_name":"Prana Flow ",
    "class_id":378,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Pixie",
    "teacher_name":"Pixie",
    "class_start":"9:30 AM",
    "class_end":"11:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":8,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Prana Flow is an energetic, creative, full-spectrum approach to embodying the flow of yoga cultivated by Shiva Rea and the Global Vinyasa Collective of Teachers. Students of all levels are empowered to experience prana – the universal source of breath, life energy and conscious intelligence – as the navigating source of yoga practice and vital living. Practitioners learn classical and innovative approaches to vinyasa yoga and the state of flow drawn from Krishnamacharya’s teachings, Tantra, Ayurveda, Bhakti, Somatics and Shiva’s teaching experience from the last fifteen years.",
    "node_music":""
  },
  {
    "class_name":"All Levels Power Vinyasa Yoga ",
    "class_id":379,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Nuria",
    "class_start":"12:00 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":8,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Yoga",
    "class_id":380,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Jasha",
    "teacher_name":"Jasha",
    "class_start":"12:15 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "attr_tempo":4,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"yo•ga | ˈyōgə | unión | • Asana ~ postures • Pranayama ~ breath control • Mantra ~ sound • Meditation ~ stillness Experience balance and peace in this hour long class. Focus your attention inward while we will take the traditional practice of yoga into a modern design, tailored to our community. Each day will be different. Whether you come once a month or three times a week, It will be well rounded and include a theme that rotates weekly to include all aspects of yoga, physical and non-physical, each month. Join in this sweet practice, honoring the full spectrum of life and ourselves.",
    "node_music":""
  },
  {
    "class_name":"Yoga Schmoga ~ Community Class",
    "class_id":381,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Patrick",
    "class_start":"3:30 PM",
    "class_end":"4:45 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":3,
    "attr_flex":6,
    "attr_balance":7,
    "attr_tempo":4,
    "difficulty":1,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Mindful movement and breath. Yoga for everybody. ~ This is a community class and available by donation.",
    "node_music":""
  },
  {
    "class_name":"Conscious Kick Boxing",
    "class_id":382,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Briana",
    "teacher_name":"Briana",
    "class_start":"5:00 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":10,
    "attr_flex":7,
    "attr_balance":8,
    "attr_tempo":10,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"",
    "node_music":""
  },
  {
    "class_name":"Slow Motion",
    "class_id":383,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_start":"5:15 PM",
    "class_end":"6:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":6,
    "attr_tempo":5,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Conscious vinyasa flow with music to wake you up from the inside out. Heavy focus on breath work to build the inner fire and asanas to strengthen and awaken the body. This class is meant to serve all students.",
    "node_music":""
  },
  {
    "class_name":"Power Vinyasa Level 2/3",
    "class_id":384,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":10,
    "attr_flex":9,
    "attr_balance":10,
    "attr_tempo":9,
    "difficulty":3,
    "node_heated":10,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students including vigorous sequences and advanced postures. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Heated to enhance flexibility and endurance. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Restorative Yoga",
    "class_id":385,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Nitsa",
    "class_start":"6:45 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":3,
    "attr_flex":2,
    "attr_balance":1,
    "attr_tempo":1,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":0,
    "node_beginner":1,
    "class_description":"Renew your energy. Rest, breathe & be. Learn to heal yourself. A class designed for deep release, expansion & freedom. Sequences coreographed to open & heal the body, soul & mind. Work with your breath & awareness to create a radical Sequences coreographed to open & heal the body, soul & mind. Work with your breath & awareness to create a radical shift in your being.",
    "node_music":""
  },
  {
    "class_name":"Partner Yoga & Flying",
    "class_id":386,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Arianna",
    "class_start":"8:15 PM",
    "class_end":"9:40 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":1,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":2,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":10,
    "attr_tempo":8,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":0,
    "node_beginner":1,
    "class_description":"With an emphasis on trust, communication, compassion, and fun, this class will teach you the fundamentals of partner stretching, Thai massage, flying, basing, and spotting. We will be focusing on the therapeutics of flying while incorporating some acrobatics as well. Come alone or with a partner- all ages and levels of practice are welcome!",
    "node_music":""
  },
  {
    "class_name":"Hathalini ",
    "class_id":387,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Chyla & Kirtan",
    "class_start":"7:45 AM",
    "class_end":"9:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":5,
    "attr_flex":6,
    "attr_balance":5,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Hathalini combines Hatha flow and Kundalini kriyas. Expect to be stretched, strengthened. Energized and uplifted . As two teachers join to celebrate yoga. Chyla and Kirtan will guide you through a class that is unique and fun.",
    "node_music":""
  },
  {
    "class_name":"Yoga and Meditation",
    "class_id":388,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Peggy",
    "class_start":"9:15 AM",
    "class_end":"10:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":5,
    "attr_flex":5,
    "attr_balance":3,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":0,
    "node_spirit":0,
    "node_beginner":1,
    "class_description":"This class explores both the physical power and transformative potential of yoga, and encourages students to develop mindfulness, confidence, and compassion through an emphasis on the breath and body alignment. It is suitable for yogis of any level of experience. Modifications to poses are offered throughout, allowing students to benefit from every pose. Each class is designed to open and strengthen even the most resistant bodies, and the supportive and compassionate environment, with an emphasis on alignment, allows students to work towards their personal edge without fear of injury. In Yoga and Meditation, students work with asana, pranayama and meditation to experience the power of yoga. Come see how this power affects our lives both on and off the mat.",
    "node_music":""
  },
  {
    "class_name":"Pilates-Yoga Fusion, Hot Level 2",
    "class_id":389,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Arianna",
    "class_start":"9:30 AM",
    "class_end":"10:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":8,
    "attr_flex":7,
    "attr_balance":8,
    "attr_tempo":8,
    "difficulty":2,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Strengthen core muscles; improve coordination, balance, and posture, gain tone, grace, and flexibility. Breathe deeply; release tension; develop profound awareness and mind-body connection. You will feel and function better all-around! Class includes: options for working and different levels so you meet your body’s ever changing needs; precise alignment descriptions + creative visualizations so you move safely, effectively, with joy and humor; varied sequencing so you are thoroughly engaged from head to toe; and a restorative cool-down and deeply delicious relaxation, so you finish fully refreshed and energized. All levels welcome!",
    "node_music":""
  },
  {
    "class_name":"All Levels Power Vinyasa Yoga ",
    "class_id":390,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"12:00 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Vinyasa Basics ",
    "class_id":391,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Asha",
    "class_start":"12:15 PM",
    "class_end":"1:30 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "attr_tempo":7,
    "difficulty":1,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Vinyasa Basics, blending Vinyasa flow with Alignment, experience the body in its element! Breathe, Body and Mind in Union. We will break down the Asana’s (poses) and flow through the basics of Yoga with Grace and Ease.",
    "node_music":""
  },
  {
    "class_name":"Power Vinyasa",
    "class_id":392,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Yoni",
    "class_start":"3:30 PM",
    "class_end":"4:45 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Yoni Berk teaches a strong vinyasa flow class designed to build a complete and solid yogic practice. With a focus on the breathe, attention to alignment, and creative sequencing, Yoni will guide you through understanding the dynamics of a strong vinyasa flow. Fusing introspective focus and light heartedness, learn to ease the mind through challenging the body. With a background in music, Yoni’s unique playlists are a draw for many student. Come for the yoga, stay for the music.",
    "node_music":""
  },
  {
    "class_name":"Aroma Slow Flow Yoga",
    "class_id":393,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Jenn",
    "class_start":"3:45 PM",
    "class_end":"5:00 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":3,
    "attr_flex":4,
    "attr_balance":3,
    "attr_tempo":3,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Aroma Slow Flow Yoga- Where Yoga and Aromatherapy meet! This 75 minute class will delight your senses physically, mentally and aromatically through a moderately paced all level slow flow practice. Each week an exciting scent will be diffused in the classroom with a specific theme. Some of the themes are emotional, some physical. The class will end with an essential oil rubbed into your temples in savasana (final resting pose)….it’s like having yoga, meditation and a spa day all within a in 75 minute period* This is an ALL LEVEL class.",
    "node_music":""
  },
  {
    "class_name":"Power Vinyasa Level 2/3",
    "class_id":394,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_start":"5:00 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":10,
    "attr_flex":10,
    "attr_balance":10,
    "attr_tempo":10,
    "difficulty":2,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students including vigorous sequences and advanced postures. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Heated to enhance flexibility and endurance. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Vinyasa Flow",
    "class_id":395,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_start":"5:15 PM",
    "class_end":"6:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":7,
    "attr_flex":8,
    "attr_balance":8,
    "attr_tempo":10,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students and modifications for newer students. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm.",
    "node_music":""
  },
  {
    "class_name":"Prana Flow",
    "class_id":396,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Pixie",
    "teacher_name":"Pixie",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":8,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Prana Flow is an energetic, creative, full-spectrum approach to embodying the flow of yoga cultivated by Shiva Rea and the Global Vinyasa Collective of Teachers. Students of all levels are empowered to experience prana – the universal source of breath, life energy and conscious intelligence – as the navigating source of yoga practice and vital living. Practitioners learn classical and innovative approaches to vinyasa yoga and the state of flow drawn from Krishnamacharya’s teachings, Tantra, Ayurveda, Bhakti, Somatics and Shiva’s teaching experience from the last fifteen years.",
    "node_music":""
  },
  {
    "class_name":"Restorative Kundalini Yoga and Meditation",
    "class_id":397,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Amanda",
    "teacher_name":"Amanda",
    "class_start":"6:45 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":1,
    "day_4":0,
    "day_5":0,
    "day_6":0,
    "class_day":3,
    "attr_strength":3,
    "attr_flex":3,
    "attr_balance":3,
    "attr_tempo":3,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":0,
    "node_beginner":1,
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam.",
    "node_music":""
  },
  {
    "class_name":"Vinyasa ",
    "class_id":399,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Tiff",
    "teacher_name":"Tiff",
    "class_start":"6:00 AM",
    "class_end":"7:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":7,
    "attr_flex":8,
    "attr_balance":8,
    "attr_tempo":10,
    "difficulty":3,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Good Morning Power Flow",
    "class_id":401,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Aliza",
    "teacher_name":"Aliza",
    "class_start":"8:00 AM",
    "class_end":"9:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":9,
    "attr_flex":7,
    "attr_balance":5,
    "attr_tempo":8,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Start your day off with an awakening and uplifting yoga class to create more positivity and less stress throughout your day. A multi-level class designed for new and experienced students. There will be progressive options offered in many asanas so that each person will be challenged at their level. A variety of new asanas will be practiced each class to explore and build upon your current practice. Expect a dynamic class to awaken your body, mind and spirit.",
    "node_music":""
  },
  {
    "class_name":"Slow Motion",
    "class_id":402,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_start":"9:30 AM",
    "class_end":"10:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":5,
    "attr_flex":4,
    "attr_balance":5,
    "attr_tempo":4,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Conscious vinyasa flow with music to wake you up from the inside out. Heavy focus on breath work to build the inner fire and asanas to strengthen and awaken the body. This class is meant to serve all students.",
    "node_music":""
  },
  {
    "class_name":"Vinyasa/Medical Chi Gong",
    "class_id":403,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_start":"10:30 AM",
    "class_end":"11:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":6,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Combining elements of Vinyasa Flow and Qi-Gong, Rachel seamlessly guides you through the inner landscapes of breath while cultivating the grandness of your Sacred Life Force.",
    "node_music":""
  },
  {
    "class_name":"All Levels Power Vinyasa Yoga",
    "class_id":404,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_start":"12:00 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":8,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Yoga ",
    "class_id":405,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Jasha",
    "teacher_name":"Jasha",
    "class_start":"12:15 PM",
    "class_end":"1:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"yo•ga | ˈyōgə | unión | • Asana ~ postures • Pranayama ~ breath control • Mantra ~ sound • Meditation ~ stillness Experience balance and peace in this hour long class. Focus your attention inward while we will take the traditional practice of yoga into a modern design, tailored to our community. Each day will be different. Whether you come once a month or three times a week, It will be well rounded and include a theme that rotates weekly to include all aspects of yoga, physical and non-physical, each month. Join in this sweet practice, honoring the full spectrum of life and ourselves.",
    "node_music":""
  },
  {
    "class_name":"All Levels Power Vinyasa Yoga",
    "class_id":406,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Rachel Meisler",
    "class_start":"3:30 PM",
    "class_end":"4:45 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Power Vinyasa All Levels",
    "class_id":408,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"candice",
    "teacher_name":"Candice",
    "class_start":"5:00 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "attr_tempo":8,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"“Sweating is meditating!” In Power Vinyasa, incorporates a fitness centered approach to yoga that focuses on maximizing the human body’s potential. Each class will be designed to synchronize breath with a series of poses. Advanced poses will be offered, but modifications will always be available. This class is meant to create the strength and flexibility that is essential for injury prevention and overall wellness. This is a great class for athletes and for those looking to improve their fitness level. Be prepared for a heated, fun, high energy vinyasa flow with movement-inspiring beats from around the world.",
    "node_music":""
  },
  {
    "class_name":"Kundalini",
    "class_id":409,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Mitsuko",
    "class_start":"5:15 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":3,
    "attr_flex":3,
    "attr_balance":3,
    "attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam.",
    "node_music":""
  },
  {
    "class_name":"Restorative & Yin Yoga",
    "class_id":410,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"deborah",
    "teacher_name":"Deborah",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":1,
    "day_5":0,
    "day_6":0,
    "class_day":4,
    "attr_strength":1,
    "attr_flex":6,
    "attr_balance":3,
    "attr_tempo":1,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"A deeply calming practice of sustained and supported poses to open the body, gently release tension in the connective tissues, bring us into the moment, and heighten awareness of our true essence. Nourish and restore while settling the mind and enlivening the Spirit. All are welcome.",
    "node_music":""
  },
  {
    "class_name":"Morning Practice",
    "class_id":412,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"Vikki",
    "teacher_name":"Vikki",
    "class_start":"9:15 AM",
    "class_end":"10:30 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":1,
    "day_6":0,
    "class_day":5,
    "attr_strength":3,
    "attr_flex":0,
    "attr_balance":0,
    "attr_tempo":3,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"The morning practice provides a space in which every student can deepen their connection with themselves.Our morning practice will always be different in content, reflecting the consistent change with life.This class has been structured for internal expansion, liberation from restrictions as well as a powerful connection to the divine essence that surrounds us all.All levels are welcomed, everyone will benefit from taking part.The practice is based on Kundalini, Naam and Sattva Yoga.",
    "node_music":""
  },
  {
    "class_name":"Power Vinyasa Level 2/3",
    "class_id":413,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"9:30 AM",
    "class_end":"11:00 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":1,
    "day_6":0,
    "class_day":5,
    "attr_strength":10,
    "attr_flex":10,
    "attr_balance":9,
    "attr_tempo":9,
    "difficulty":3,
    "node_heated":1,
    "node_injuries":0,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"An empowering, energetic flow that builds strength and balance inside and out, with challenges for advanced students including vigorous sequences and advanced postures. Through continuous movement and attention to breath, the moving meditation awakens awareness while inspires calm. Heated to enhance flexibility and endurance. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Shimmy, Shake and Flow ",
    "class_id":414,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Arianna",
    "class_start":"11:15 AM",
    "class_end":"12:30 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":1,
    "day_6":0,
    "class_day":5,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":6,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"In its profoundest sense, to Dance is to know oneself. Belly Dancing has many elements in common with yoga. Mentally, Yoga allows for “letting go and letting flow”. To expand one’s consciousness the Belly Dancer must at a very fundamental level become aware of dense places in her body and through the practice of yoga invite expansion into those areas. Humans are innately creative. The first Chakra, which is located in the pelvis, is the creativity center. With a strong emphasis on hip and pelvic movements, Belly dancing activates our creativity. In this class, we flow through vinyasa practice to stretch and strengthen the body, then we explore isolations through belly dance. Yoga teaches one to move consciously, while Belly dance demonstrates how we could tap into our creative consciousness.",
    "node_music":""
  },
  {
    "class_name":"Power Vinyasa All Levels ",
    "class_id":415,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"chyla",
    "teacher_name":"Chyla",
    "class_start":"11:30 AM",
    "class_end":"12:45 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":1,
    "day_6":0,
    "class_day":5,
    "attr_strength":7,
    "attr_flex":6,
    "attr_balance":6,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"“Sweating is meditating!” In Power Vinyasa, incorporates a fitness centered approach to yoga that focuses on maximizing the human body’s potential. Each class will be designed to synchronize breath with a series of poses. Advanced poses will be offered, but modifications will always be available. This class is meant to create the strength and flexibility that is essential for injury prevention and overall wellness. This is a great class for athletes and for those looking to improve their fitness level. Be prepared for a heated, fun, high energy vinyasa flow with movement-inspiring beats from around the world.",
    "node_music":""
  },
  {
    "class_name":"Qi Gong ",
    "class_id":417,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Russell",
    "class_start":"4:30 PM",
    "class_end":"6:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":1,
    "day_6":0,
    "class_day":5,
    "attr_strength":6,
    "attr_flex":5,
    "attr_balance":7,
    "attr_tempo":4,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"",
    "node_music":""
  },
  {
    "class_name":"Vinyasa Basics ",
    "class_id":418,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Sarah",
    "teacher_name":"Sarah",
    "class_start":"4:30 PM",
    "class_end":"6:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":1,
    "day_6":0,
    "class_day":5,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":8,
    "attr_tempo":7,
    "difficulty":1,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Vinyasa Basics, blending Flow with Alignment, experience the body in its element! Breath, Body and Mind in Union. We will break down the Asana’s (poses) and flow through the basics of Yoga with Grace and Ease. Classes are joyous and infused with a sense of play. Good for experienced students and beginners alike who are looking for a deeper understanding of the poses in your body and connection of breath with movement.",
    "node_music":""
  },
  {
    "class_name":"Liquid Flow with Sacred Sound",
    "class_id":420,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Rachel Petkus",
    "class_start":"9:15 AM",
    "class_end":"10:30 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":5,
    "attr_flex":6,
    "attr_balance":6,
    "attr_tempo":5,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"",
    "node_music":""
  },
  {
    "class_name":"Kundalini ",
    "class_id":421,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Kirtan",
    "class_start":"9:30 AM",
    "class_end":"10:45 AM",
    "node_morning":1,
    "node_afternoon":0,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":5,
    "attr_flex":6,
    "attr_balance":5,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"Kundalini yoga is a great way to take any practice to the next level, or a practice in it of itself. Each class consists of the simple yet powerful combination of breath work, movement, meditation, sound, and relaxation. Benefits include stimulating the nervous system, improving strength and flexibility, and finding peace. From beginners to advanced practitioners, kundalini yoga is an excellent gateway to activate the subtle energy body, quite the mind, and remove emotional blockages that prevent us from experiencing the joy, peace, love and vibrant, radiant live that we all desire and deserve. Sat Nam.",
    "node_music":""
  },
  {
    "class_name":"All Levels Power Vinyasa Yoga",
    "class_id":422,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Nuria",
    "teacher_name":"Nuria",
    "class_start":"11:00 AM",
    "class_end":"12:15 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Creative sequencing offers fluid movements as if in a dance. Clear cues for correct alignment. Options offered within the practice for beginning to advanced practitioners. Strong poses bring flexibility and openness while meditation and breath-work bring clarity. Come ready to breath, sweat, and open up! Heated 85-90 degrees.",
    "node_music":""
  },
  {
    "class_name":"Power Vinyasa ",
    "class_id":424,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"",
    "teacher_name":"Amanda",
    "class_start":"1:00 PM",
    "class_end":"2:30 PM",
    "node_morning":0,
    "node_afternoon":1,
    "node_night":0,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"Yoni Berk teaches a strong vinyasa flow class designed to build a complete and solid yogic practice. With a focus on the breathe, attention to alignment, and creative sequencing, Yoni will guide you through understanding the dynamics of a strong vinyasa flow. Fusing introspective focus and light heartedness, learn to ease the mind through challenging the body. With a background in music, Yoni’s unique playlists are a draw for many student. Come for the yoga, stay for the music.",
    "node_music":""
  },
  {
    "class_name":"Capoeira Pacifica",
    "class_id":425,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Sean",
    "class_start":"4:00 PM",
    "class_end":"5:30 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":5,
    "attr_flex":7,
    "attr_balance":9,
    "attr_tempo":8,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":0,
    "node_stand":0,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":0,
    "node_beginner":1,
    "class_description":"Capoeira is a unique Afro-Brazilian martial art dating back to the 16th century with a growth in popularity in recent years. Movements are graceful, dance-like combinations of kicks, throws, acrobatics, and ground movements that enhance awareness, flexibility, and strength. When learning Capoeira, a student will be exposed to a fighting style, music, and the Brazilian culture. Capoeira is most of all very fun and is a great workout for the body and the mind!",
    "node_music":""
  },
  {
    "class_name":"Eclectic Flow",
    "class_id":426,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Brett",
    "teacher_name":"Brett",
    "class_start":"5:00 PM",
    "class_end":"6:15 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":6,
    "attr_flex":6,
    "attr_balance":7,
    "attr_tempo":6,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":1,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"A strong mix of ashtanga, bikram, and iyengar poses with pranayama. Temp 87degrees.",
    "node_music":""
  },
  {
    "class_name":"Kirtan and Sacred Music",
    "class_id":427,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Moon Room",
    "teacher_image":"",
    "teacher_name":"Jacob",
    "class_start":"6:00 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":0,
    "attr_flex":0,
    "attr_balance":0,
    "attr_tempo":0,
    "difficulty":0,
    "node_heated":0,
    "node_injuries":1,
    "node_stand":0,
    "node_meditation":1,
    "node_chanting":1,
    "node_core":0,
    "node_spirit":1,
    "node_beginner":1,
    "class_description":"COMMUNITY EVENT EVERY 7! Devotional singing guides us into incredible states of meditation and bliss. Ancient sanskrit mantras are rendered into traditional melodies and accompanied by shamanic drum beats. The kirtan leader sings the call and the audience sings the response for a truly interactive musical experience where an entire room of people create healing intentions and positive expressions. The focus of the chants are Hindu deities – symbols of the ideal intentions we wish to bring into our lives. This beautiful practice is recognized in the yoga community as the quickest path to bliss, harmony and enlightenment.Suggested $15-20 Love Donation",
    "node_music":""
  },
  {
    "class_name":"Vinyasa Flow - Community Class ",
    "class_id":428,
    "studio_id":8,
    "studio_name":"Divinitree",
    "room_name":"Sun Room",
    "teacher_image":"Rachel",
    "teacher_name":"Rachel Wilkins",
    "class_start":"6:30 PM",
    "class_end":"8:00 PM",
    "node_morning":0,
    "node_afternoon":0,
    "node_night":1,
    "day_0":0,
    "day_1":0,
    "day_2":0,
    "day_3":0,
    "day_4":0,
    "day_5":0,
    "day_6":1,
    "class_day":6,
    "attr_strength":7,
    "attr_flex":7,
    "attr_balance":7,
    "attr_tempo":7,
    "difficulty":0,
    "node_heated":1,
    "node_injuries":1,
    "node_stand":1,
    "node_meditation":0,
    "node_chanting":0,
    "node_core":1,
    "node_spirit":1,
    "node_beginner":0,
    "class_description":"In this breath centered, core strengthening vinyasa flow class students will be given the space and support to safely deepen their practice. Breath, sweat, play and donate what you can. All levels and practices welcome.",
    "node_music":""
  }
];